import { useMemo } from "react";

/**
 * DottedMap — a stylized dotted world map.
 *
 * Rebuilt: rather than a hand-drawn ASCII mask, the dot grid is generated by
 * testing each cell's geographic center against a set of continent polygons.
 * The resulting shapes read much closer to a real Robinson-ish world map at
 * low resolution while remaining lightweight (a few hundred SVG circles).
 */

// Continent outlines, each an array of [lon, lat] vertices, roughly tracing
// real coastlines. These are intentionally coarse — the dot grid softens them.
const CONTINENTS: Array<[number, number][]> = [
  // North America (incl. Alaska)
  [
    [-168, 66], [-158, 71], [-140, 70], [-125, 70], [-95, 74], [-80, 73],
    [-65, 60], [-55, 52], [-60, 47], [-70, 45], [-80, 45], [-82, 30],
    [-90, 29], [-97, 26], [-105, 22], [-110, 30], [-118, 33], [-124, 40],
    [-124, 48], [-132, 54], [-150, 59], [-165, 60], [-168, 66],
  ],
  // Central America
  [
    [-97, 25], [-90, 21], [-83, 15], [-79, 8], [-77, 8], [-82, 14],
    [-88, 17], [-92, 18], [-97, 25],
  ],
  // South America
  [
    [-80, 12], [-70, 12], [-60, 8], [-52, 5], [-45, 0], [-38, -5],
    [-38, -14], [-40, -22], [-48, -28], [-58, -35], [-65, -43],
    [-70, -52], [-74, -52], [-75, -46], [-72, -38], [-72, -25],
    [-76, -14], [-80, -5], [-80, 3], [-80, 12],
  ],
  // Greenland
  [
    [-55, 60], [-42, 60], [-25, 65], [-18, 72], [-25, 80], [-45, 82],
    [-55, 75], [-58, 68], [-55, 60],
  ],
  // Europe (mainland)
  [
    [-10, 44], [-5, 43], [0, 44], [8, 44], [15, 40], [20, 40], [28, 41],
    [30, 45], [35, 47], [40, 50], [40, 55], [30, 60], [22, 60], [15, 58],
    [8, 55], [0, 52], [-5, 50], [-10, 50], [-10, 44],
  ],
  // Scandinavia
  [
    [5, 58], [8, 63], [12, 68], [22, 70], [30, 71], [30, 66], [24, 62],
    [18, 60], [10, 58], [5, 58],
  ],
  // UK & Ireland (approx)
  [
    [-10, 51], [-6, 55], [-4, 58], [0, 58], [2, 53], [-2, 50], [-10, 51],
  ],
  // Africa
  [
    [-17, 32], [-10, 34], [0, 35], [10, 35], [22, 32], [33, 31], [35, 22],
    [42, 15], [50, 12], [51, 5], [45, -5], [40, -15], [37, -22], [32, -30],
    [25, -34], [18, -34], [12, -25], [8, -8], [4, 4], [-6, 4], [-12, 12],
    [-17, 20], [-17, 32],
  ],
  // Arabia (kept slightly separate from Asia so the gulf reads)
  [
    [35, 30], [43, 30], [50, 25], [55, 22], [55, 16], [50, 12], [43, 13],
    [38, 20], [35, 24], [35, 30],
  ],
  // Asia (main mass, Ural → Kamchatka)
  [
    [40, 55], [50, 60], [65, 66], [80, 70], [100, 72], [125, 72], [145, 70],
    [165, 65], [178, 65], [178, 55], [160, 55], [145, 55], [140, 50],
    [138, 45], [130, 40], [125, 38], [122, 30], [118, 22], [110, 20],
    [104, 22], [100, 24], [95, 26], [88, 28], [78, 32], [70, 40],
    [58, 42], [50, 44], [45, 48], [42, 52], [40, 55],
  ],
  // India
  [
    [68, 24], [75, 30], [80, 28], [88, 24], [90, 22], [82, 12], [78, 8],
    [72, 12], [68, 20], [68, 24],
  ],
  // SE Asia + Indonesia (simplified)
  [
    [95, 22], [102, 18], [108, 14], [110, 5], [105, -2], [100, 0], [96, 5],
    [95, 12], [95, 22],
  ],
  [
    [95, 4], [110, 2], [120, -4], [130, -6], [140, -8], [140, 0], [125, 6],
    [112, 6], [100, 6], [95, 4],
  ],
  // Australia
  [
    [113, -22], [122, -17], [135, -13], [143, -12], [150, -18], [153, -28],
    [148, -37], [140, -38], [130, -32], [118, -35], [114, -30], [113, -22],
  ],
  // New Zealand
  [
    [166, -46], [172, -41], [176, -37], [178, -40], [174, -46], [170, -47], [166, -46],
  ],
  // Japan
  [
    [130, 33], [134, 34], [138, 36], [141, 39], [142, 43], [145, 45],
    [141, 45], [136, 37], [131, 34], [130, 33],
  ],
];

function pointInPolygon(lon: number, lat: number, poly: [number, number][]) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    const intersect = yi > lat !== yj > lat &&
      lon < ((xj - xi) * (lat - yi)) / (yj - yi + 1e-9) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

function isLand(lon: number, lat: number) {
  for (const p of CONTINENTS) if (pointInPolygon(lon, lat, p)) return true;
  return false;
}

type CityPulse = { name?: string; lon: number; lat: number };

const DEFAULT_CITIES: CityPulse[] = [
  { name: "New York", lon: -74.0, lat: 40.7 },
  { name: "São Paulo", lon: -46.6, lat: -23.5 },
  { name: "London", lon: -0.13, lat: 51.5 },
  { name: "Lagos", lon: 3.4, lat: 6.5 },
  { name: "Cape Town", lon: 18.4, lat: -33.9 },
  { name: "Berlin", lon: 13.4, lat: 52.5 },
  { name: "Delhi", lon: 77.2, lat: 28.6 },
  { name: "Tokyo", lon: 139.7, lat: 35.7 },
  { name: "Singapore", lon: 103.8, lat: 1.35 },
  { name: "Sydney", lon: 151.2, lat: -33.9 },
];

// Grid resolution. Higher = more dots, more detailed silhouette.
const COLS = 110;
const ROWS = 46;
const LON_MIN = -170;
const LON_MAX = 180;
const LAT_MAX = 78;
const LAT_MIN = -56;

function cellToLonLat(x: number, y: number) {
  const lon = LON_MIN + ((x + 0.5) / COLS) * (LON_MAX - LON_MIN);
  const lat = LAT_MAX - ((y + 0.5) / ROWS) * (LAT_MAX - LAT_MIN);
  return { lon, lat };
}

function lonLatToXY(lon: number, lat: number) {
  const x = ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * COLS;
  const y = ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * ROWS;
  return { x, y };
}

export function DottedMap({
  className = "",
  dotColor = "rgba(226,226,226,0.32)",
  pulseColor = "#F0A968",
  cities = DEFAULT_CITIES,
  step = 10,
}: {
  className?: string;
  dotColor?: string;
  pulseColor?: string;
  cities?: CityPulse[];
  step?: number;
}) {
  const dots = useMemo(() => {
    const out: Array<{ x: number; y: number }> = [];
    for (let y = 0; y < ROWS; y++) {
      for (let x = 0; x < COLS; x++) {
        const { lon, lat } = cellToLonLat(x, y);
        if (isLand(lon, lat)) out.push({ x, y });
      }
    }
    return out;
  }, []);

  const width = COLS * step;
  const height = ROWS * step;
  const r = Math.max(1.2, step * 0.18);

  const pulses = cities.map((c) => {
    const { x, y } = lonLatToXY(c.lon, c.lat);
    return { cx: x * step, cy: y * step, name: c.name };
  });

  const equatorY = ((LAT_MAX - 0) / (LAT_MAX - LAT_MIN)) * height;

  return (
    <svg
      aria-hidden="true"
      viewBox={`0 0 ${width} ${height}`}
      className={`w-full h-auto ${className}`}
      preserveAspectRatio="xMidYMid meet"
    >
      <line
        x1="0"
        x2={width}
        y1={equatorY}
        y2={equatorY}
        stroke="rgba(226,226,226,0.05)"
        strokeDasharray="2 6"
      />
      {dots.map((d, i) => (
        <circle
          key={i}
          cx={d.x * step + step / 2}
          cy={d.y * step + step / 2}
          r={r}
          fill={dotColor}
        />
      ))}
      {pulses.map((p, i) => (
        <g key={`p-${i}`}>
          <circle
            cx={p.cx}
            cy={p.cy}
            r={r * 2.6}
            fill={pulseColor}
            opacity={0.95}
            style={{ filter: `drop-shadow(0 0 10px ${pulseColor})` }}
          />
          <circle
            cx={p.cx}
            cy={p.cy}
            r={r * 2.6}
            fill="none"
            stroke={pulseColor}
            strokeOpacity={0.6}
            style={{
              transformOrigin: `${p.cx}px ${p.cy}px`,
              animation: `map-pulse 3.4s ease-out ${i * 0.35}s infinite`,
            }}
          />
        </g>
      ))}
    </svg>
  );
}
