/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedCapsuleRouteImport } from './routes/_authenticated/capsule'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedCirclesRouteImport } from './routes/_authenticated/circles'
import { Route as AuthenticatedCompanionRouteImport } from './routes/_authenticated/companion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReplayRouteImport } from './routes/_authenticated/replay'
import { Route as AuthenticatedSeasonsRouteImport } from './routes/_authenticated/seasons'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedWrappedRouteImport } from './routes/_authenticated/wrapped'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated/profile.$id'
import { Route as AuthenticatedRoomCodeRouteImport } from './routes/_authenticated/room.$code'
import { Route as AuthenticatedTrustModerationRouteImport } from './routes/_authenticated/trust.moderation'
import { Route as ApiPublicAuthGuardRouteImport } from './routes/api/public/auth-guard'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicAiCompanionRouteImport } from './routes/api/public/ai/companion'
import { Route as ApiPublicAiDashboardInsightsRouteImport } from './routes/api/public/ai/dashboard-insights'
import { Route as ApiPublicAiDiscoverPatternsRouteImport } from './routes/api/public/ai/discover-patterns'
import { Route as ApiPublicAiProactiveRouteImport } from './routes/api/public/ai/proactive'
import { Route as ApiPublicAiRecommendRouteImport } from './routes/api/public/ai/recommend'
import { Route as ApiPublicAiSessionRecapRouteImport } from './routes/api/public/ai/session-recap'
import { Route as ApiPublicAiVaultSummarizeRouteImport } from './routes/api/public/ai/vault-summarize'
import { Route as ApiPublicAiWeeklyStoryRouteImport } from './routes/api/public/ai/weekly-story'
import { Route as ApiPublicAuthGuardSigninRouteImport } from './routes/api/public/auth-guard.signin'
import { Route as ApiPublicWebhooksCreateRouteImport } from './routes/api/public/webhooks/create'
import { Route as ApiPublicWebhooksDeleteRouteImport } from './routes/api/public/webhooks/delete'
import { Route as ApiPublicWebhooksDeliveriesRouteImport } from './routes/api/public/webhooks/deliveries'
import { Route as ApiPublicWebhooksListRouteImport } from './routes/api/public/webhooks/list'
import { Route as ApiPublicWebhooksTestRouteImport } from './routes/api/public/webhooks/test'
import { Route as ApiPublicWebhooksToggleRouteImport } from './routes/api/public/webhooks/toggle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapsuleRoute = AuthenticatedCapsuleRouteImport.update({
  id: '/capsule',
  path: '/capsule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirclesRoute = AuthenticatedCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanionRoute = AuthenticatedCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReplayRoute = AuthenticatedReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonsRoute = AuthenticatedSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWrappedRoute = AuthenticatedWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProfileRoute,
} as any)
const AuthenticatedRoomCodeRoute = AuthenticatedRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustModerationRoute =
  AuthenticatedTrustModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedTrustRoute,
  } as any)
const ApiPublicAuthGuardRoute = ApiPublicAuthGuardRouteImport.update({
  id: '/api/public/auth-guard',
  path: '/api/public/auth-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiCompanionRoute = ApiPublicAiCompanionRouteImport.update({
  id: '/api/public/ai/companion',
  path: '/api/public/ai/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiDashboardInsightsRoute =
  ApiPublicAiDashboardInsightsRouteImport.update({
    id: '/api/public/ai/dashboard-insights',
    path: '/api/public/ai/dashboard-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiDiscoverPatternsRoute =
  ApiPublicAiDiscoverPatternsRouteImport.update({
    id: '/api/public/ai/discover-patterns',
    path: '/api/public/ai/discover-patterns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiProactiveRoute = ApiPublicAiProactiveRouteImport.update({
  id: '/api/public/ai/proactive',
  path: '/api/public/ai/proactive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiRecommendRoute = ApiPublicAiRecommendRouteImport.update({
  id: '/api/public/ai/recommend',
  path: '/api/public/ai/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiSessionRecapRoute = ApiPublicAiSessionRecapRouteImport.update({
  id: '/api/public/ai/session-recap',
  path: '/api/public/ai/session-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiVaultSummarizeRoute =
  ApiPublicAiVaultSummarizeRouteImport.update({
    id: '/api/public/ai/vault-summarize',
    path: '/api/public/ai/vault-summarize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiWeeklyStoryRoute = ApiPublicAiWeeklyStoryRouteImport.update({
  id: '/api/public/ai/weekly-story',
  path: '/api/public/ai/weekly-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthGuardSigninRoute =
  ApiPublicAuthGuardSigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => ApiPublicAuthGuardRoute,
  } as any)
const ApiPublicWebhooksCreateRoute = ApiPublicWebhooksCreateRouteImport.update({
  id: '/api/public/webhooks/create',
  path: '/api/public/webhooks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDeleteRoute = ApiPublicWebhooksDeleteRouteImport.update({
  id: '/api/public/webhooks/delete',
  path: '/api/public/webhooks/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDeliveriesRoute =
  ApiPublicWebhooksDeliveriesRouteImport.update({
    id: '/api/public/webhooks/deliveries',
    path: '/api/public/webhooks/deliveries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksListRoute = ApiPublicWebhooksListRouteImport.update({
  id: '/api/public/webhooks/list',
  path: '/api/public/webhooks/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksTestRoute = ApiPublicWebhooksTestRouteImport.update({
  id: '/api/public/webhooks/test',
  path: '/api/public/webhooks/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksToggleRoute = ApiPublicWebhooksToggleRouteImport.update({
  id: '/api/public/webhooks/toggle',
  path: '/api/public/webhooks/toggle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/sdk': typeof SdkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/capsule': typeof AuthenticatedCapsuleRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/circles': typeof AuthenticatedCirclesRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/replay': typeof AuthenticatedReplayRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/start': typeof AuthenticatedStartRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/trust': typeof AuthenticatedTrustRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/wrapped': typeof AuthenticatedWrappedRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
  '/trust/moderation': typeof AuthenticatedTrustModerationRoute
  '/api/public/auth-guard': typeof ApiPublicAuthGuardRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/ai/companion': typeof ApiPublicAiCompanionRoute
  '/api/public/ai/dashboard-insights': typeof ApiPublicAiDashboardInsightsRoute
  '/api/public/ai/discover-patterns': typeof ApiPublicAiDiscoverPatternsRoute
  '/api/public/ai/proactive': typeof ApiPublicAiProactiveRoute
  '/api/public/ai/recommend': typeof ApiPublicAiRecommendRoute
  '/api/public/ai/session-recap': typeof ApiPublicAiSessionRecapRoute
  '/api/public/ai/vault-summarize': typeof ApiPublicAiVaultSummarizeRoute
  '/api/public/ai/weekly-story': typeof ApiPublicAiWeeklyStoryRoute
  '/api/public/auth-guard/signin': typeof ApiPublicAuthGuardSigninRoute
  '/api/public/webhooks/create': typeof ApiPublicWebhooksCreateRoute
  '/api/public/webhooks/delete': typeof ApiPublicWebhooksDeleteRoute
  '/api/public/webhooks/deliveries': typeof ApiPublicWebhooksDeliveriesRoute
  '/api/public/webhooks/list': typeof ApiPublicWebhooksListRoute
  '/api/public/webhooks/test': typeof ApiPublicWebhooksTestRoute
  '/api/public/webhooks/toggle': typeof ApiPublicWebhooksToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/sdk': typeof SdkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/capsule': typeof AuthenticatedCapsuleRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/circles': typeof AuthenticatedCirclesRoute
  '/companion': typeof AuthenticatedCompanionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/replay': typeof AuthenticatedReplayRoute
  '/seasons': typeof AuthenticatedSeasonsRoute
  '/start': typeof AuthenticatedStartRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/trust': typeof AuthenticatedTrustRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/wrapped': typeof AuthenticatedWrappedRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
  '/trust/moderation': typeof AuthenticatedTrustModerationRoute
  '/api/public/auth-guard': typeof ApiPublicAuthGuardRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/ai/companion': typeof ApiPublicAiCompanionRoute
  '/api/public/ai/dashboard-insights': typeof ApiPublicAiDashboardInsightsRoute
  '/api/public/ai/discover-patterns': typeof ApiPublicAiDiscoverPatternsRoute
  '/api/public/ai/proactive': typeof ApiPublicAiProactiveRoute
  '/api/public/ai/recommend': typeof ApiPublicAiRecommendRoute
  '/api/public/ai/session-recap': typeof ApiPublicAiSessionRecapRoute
  '/api/public/ai/vault-summarize': typeof ApiPublicAiVaultSummarizeRoute
  '/api/public/ai/weekly-story': typeof ApiPublicAiWeeklyStoryRoute
  '/api/public/auth-guard/signin': typeof ApiPublicAuthGuardSigninRoute
  '/api/public/webhooks/create': typeof ApiPublicWebhooksCreateRoute
  '/api/public/webhooks/delete': typeof ApiPublicWebhooksDeleteRoute
  '/api/public/webhooks/deliveries': typeof ApiPublicWebhooksDeliveriesRoute
  '/api/public/webhooks/list': typeof ApiPublicWebhooksListRoute
  '/api/public/webhooks/test': typeof ApiPublicWebhooksTestRoute
  '/api/public/webhooks/toggle': typeof ApiPublicWebhooksToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy': typeof PrivacyRoute
  '/sdk': typeof SdkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/capsule': typeof AuthenticatedCapsuleRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/circles': typeof AuthenticatedCirclesRoute
  '/_authenticated/companion': typeof AuthenticatedCompanionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/replay': typeof AuthenticatedReplayRoute
  '/_authenticated/seasons': typeof AuthenticatedSeasonsRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRouteWithChildren
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/wrapped': typeof AuthenticatedWrappedRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
  '/_authenticated/room/$code': typeof AuthenticatedRoomCodeRoute
  '/_authenticated/trust/moderation': typeof AuthenticatedTrustModerationRoute
  '/api/public/auth-guard': typeof ApiPublicAuthGuardRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/ai/companion': typeof ApiPublicAiCompanionRoute
  '/api/public/ai/dashboard-insights': typeof ApiPublicAiDashboardInsightsRoute
  '/api/public/ai/discover-patterns': typeof ApiPublicAiDiscoverPatternsRoute
  '/api/public/ai/proactive': typeof ApiPublicAiProactiveRoute
  '/api/public/ai/recommend': typeof ApiPublicAiRecommendRoute
  '/api/public/ai/session-recap': typeof ApiPublicAiSessionRecapRoute
  '/api/public/ai/vault-summarize': typeof ApiPublicAiVaultSummarizeRoute
  '/api/public/ai/weekly-story': typeof ApiPublicAiWeeklyStoryRoute
  '/api/public/auth-guard/signin': typeof ApiPublicAuthGuardSigninRoute
  '/api/public/webhooks/create': typeof ApiPublicWebhooksCreateRoute
  '/api/public/webhooks/delete': typeof ApiPublicWebhooksDeleteRoute
  '/api/public/webhooks/deliveries': typeof ApiPublicWebhooksDeliveriesRoute
  '/api/public/webhooks/list': typeof ApiPublicWebhooksListRoute
  '/api/public/webhooks/test': typeof ApiPublicWebhooksTestRoute
  '/api/public/webhooks/toggle': typeof ApiPublicWebhooksToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/philosophy'
    | '/privacy'
    | '/sdk'
    | '/sitemap.xml'
    | '/achievements'
    | '/capsule'
    | '/challenges'
    | '/circles'
    | '/companion'
    | '/dashboard'
    | '/dna'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/insights'
    | '/integrations'
    | '/leaderboard'
    | '/partners'
    | '/profile'
    | '/replay'
    | '/seasons'
    | '/start'
    | '/timeline'
    | '/trust'
    | '/vault'
    | '/webhooks'
    | '/wrapped'
    | '/profile/$id'
    | '/room/$code'
    | '/trust/moderation'
    | '/api/public/auth-guard'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/ai/companion'
    | '/api/public/ai/dashboard-insights'
    | '/api/public/ai/discover-patterns'
    | '/api/public/ai/proactive'
    | '/api/public/ai/recommend'
    | '/api/public/ai/session-recap'
    | '/api/public/ai/vault-summarize'
    | '/api/public/ai/weekly-story'
    | '/api/public/auth-guard/signin'
    | '/api/public/webhooks/create'
    | '/api/public/webhooks/delete'
    | '/api/public/webhooks/deliveries'
    | '/api/public/webhooks/list'
    | '/api/public/webhooks/test'
    | '/api/public/webhooks/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalog'
    | '/philosophy'
    | '/privacy'
    | '/sdk'
    | '/sitemap.xml'
    | '/achievements'
    | '/capsule'
    | '/challenges'
    | '/circles'
    | '/companion'
    | '/dashboard'
    | '/dna'
    | '/feed'
    | '/friends'
    | '/groups'
    | '/insights'
    | '/integrations'
    | '/leaderboard'
    | '/partners'
    | '/profile'
    | '/replay'
    | '/seasons'
    | '/start'
    | '/timeline'
    | '/trust'
    | '/vault'
    | '/webhooks'
    | '/wrapped'
    | '/profile/$id'
    | '/room/$code'
    | '/trust/moderation'
    | '/api/public/auth-guard'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/ai/companion'
    | '/api/public/ai/dashboard-insights'
    | '/api/public/ai/discover-patterns'
    | '/api/public/ai/proactive'
    | '/api/public/ai/recommend'
    | '/api/public/ai/session-recap'
    | '/api/public/ai/vault-summarize'
    | '/api/public/ai/weekly-story'
    | '/api/public/auth-guard/signin'
    | '/api/public/webhooks/create'
    | '/api/public/webhooks/delete'
    | '/api/public/webhooks/deliveries'
    | '/api/public/webhooks/list'
    | '/api/public/webhooks/test'
    | '/api/public/webhooks/toggle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalog'
    | '/philosophy'
    | '/privacy'
    | '/sdk'
    | '/sitemap.xml'
    | '/_authenticated/achievements'
    | '/_authenticated/capsule'
    | '/_authenticated/challenges'
    | '/_authenticated/circles'
    | '/_authenticated/companion'
    | '/_authenticated/dashboard'
    | '/_authenticated/dna'
    | '/_authenticated/feed'
    | '/_authenticated/friends'
    | '/_authenticated/groups'
    | '/_authenticated/insights'
    | '/_authenticated/integrations'
    | '/_authenticated/leaderboard'
    | '/_authenticated/partners'
    | '/_authenticated/profile'
    | '/_authenticated/replay'
    | '/_authenticated/seasons'
    | '/_authenticated/start'
    | '/_authenticated/timeline'
    | '/_authenticated/trust'
    | '/_authenticated/vault'
    | '/_authenticated/webhooks'
    | '/_authenticated/wrapped'
    | '/_authenticated/profile/$id'
    | '/_authenticated/room/$code'
    | '/_authenticated/trust/moderation'
    | '/api/public/auth-guard'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/ai/companion'
    | '/api/public/ai/dashboard-insights'
    | '/api/public/ai/discover-patterns'
    | '/api/public/ai/proactive'
    | '/api/public/ai/recommend'
    | '/api/public/ai/session-recap'
    | '/api/public/ai/vault-summarize'
    | '/api/public/ai/weekly-story'
    | '/api/public/auth-guard/signin'
    | '/api/public/webhooks/create'
    | '/api/public/webhooks/delete'
    | '/api/public/webhooks/deliveries'
    | '/api/public/webhooks/list'
    | '/api/public/webhooks/test'
    | '/api/public/webhooks/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PrivacyRoute: typeof PrivacyRoute
  SdkRoute: typeof SdkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAuthGuardRoute: typeof ApiPublicAuthGuardRouteWithChildren
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicAiCompanionRoute: typeof ApiPublicAiCompanionRoute
  ApiPublicAiDashboardInsightsRoute: typeof ApiPublicAiDashboardInsightsRoute
  ApiPublicAiDiscoverPatternsRoute: typeof ApiPublicAiDiscoverPatternsRoute
  ApiPublicAiProactiveRoute: typeof ApiPublicAiProactiveRoute
  ApiPublicAiRecommendRoute: typeof ApiPublicAiRecommendRoute
  ApiPublicAiSessionRecapRoute: typeof ApiPublicAiSessionRecapRoute
  ApiPublicAiVaultSummarizeRoute: typeof ApiPublicAiVaultSummarizeRoute
  ApiPublicAiWeeklyStoryRoute: typeof ApiPublicAiWeeklyStoryRoute
  ApiPublicWebhooksCreateRoute: typeof ApiPublicWebhooksCreateRoute
  ApiPublicWebhooksDeleteRoute: typeof ApiPublicWebhooksDeleteRoute
  ApiPublicWebhooksDeliveriesRoute: typeof ApiPublicWebhooksDeliveriesRoute
  ApiPublicWebhooksListRoute: typeof ApiPublicWebhooksListRoute
  ApiPublicWebhooksTestRoute: typeof ApiPublicWebhooksTestRoute
  ApiPublicWebhooksToggleRoute: typeof ApiPublicWebhooksToggleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsule': {
      id: '/_authenticated/capsule'
      path: '/capsule'
      fullPath: '/capsule'
      preLoaderRoute: typeof AuthenticatedCapsuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles': {
      id: '/_authenticated/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AuthenticatedCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companion': {
      id: '/_authenticated/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AuthenticatedCompanionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/replay': {
      id: '/_authenticated/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AuthenticatedReplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons': {
      id: '/_authenticated/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof AuthenticatedSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wrapped': {
      id: '/_authenticated/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AuthenticatedWrappedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/room/$code': {
      id: '/_authenticated/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof AuthenticatedRoomCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust/moderation': {
      id: '/_authenticated/trust/moderation'
      path: '/moderation'
      fullPath: '/trust/moderation'
      preLoaderRoute: typeof AuthenticatedTrustModerationRouteImport
      parentRoute: typeof AuthenticatedTrustRoute
    }
    '/api/public/auth-guard': {
      id: '/api/public/auth-guard'
      path: '/api/public/auth-guard'
      fullPath: '/api/public/auth-guard'
      preLoaderRoute: typeof ApiPublicAuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/companion': {
      id: '/api/public/ai/companion'
      path: '/api/public/ai/companion'
      fullPath: '/api/public/ai/companion'
      preLoaderRoute: typeof ApiPublicAiCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/dashboard-insights': {
      id: '/api/public/ai/dashboard-insights'
      path: '/api/public/ai/dashboard-insights'
      fullPath: '/api/public/ai/dashboard-insights'
      preLoaderRoute: typeof ApiPublicAiDashboardInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/discover-patterns': {
      id: '/api/public/ai/discover-patterns'
      path: '/api/public/ai/discover-patterns'
      fullPath: '/api/public/ai/discover-patterns'
      preLoaderRoute: typeof ApiPublicAiDiscoverPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/proactive': {
      id: '/api/public/ai/proactive'
      path: '/api/public/ai/proactive'
      fullPath: '/api/public/ai/proactive'
      preLoaderRoute: typeof ApiPublicAiProactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/recommend': {
      id: '/api/public/ai/recommend'
      path: '/api/public/ai/recommend'
      fullPath: '/api/public/ai/recommend'
      preLoaderRoute: typeof ApiPublicAiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/session-recap': {
      id: '/api/public/ai/session-recap'
      path: '/api/public/ai/session-recap'
      fullPath: '/api/public/ai/session-recap'
      preLoaderRoute: typeof ApiPublicAiSessionRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/vault-summarize': {
      id: '/api/public/ai/vault-summarize'
      path: '/api/public/ai/vault-summarize'
      fullPath: '/api/public/ai/vault-summarize'
      preLoaderRoute: typeof ApiPublicAiVaultSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/weekly-story': {
      id: '/api/public/ai/weekly-story'
      path: '/api/public/ai/weekly-story'
      fullPath: '/api/public/ai/weekly-story'
      preLoaderRoute: typeof ApiPublicAiWeeklyStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-guard/signin': {
      id: '/api/public/auth-guard/signin'
      path: '/signin'
      fullPath: '/api/public/auth-guard/signin'
      preLoaderRoute: typeof ApiPublicAuthGuardSigninRouteImport
      parentRoute: typeof ApiPublicAuthGuardRoute
    }
    '/api/public/webhooks/create': {
      id: '/api/public/webhooks/create'
      path: '/api/public/webhooks/create'
      fullPath: '/api/public/webhooks/create'
      preLoaderRoute: typeof ApiPublicWebhooksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/delete': {
      id: '/api/public/webhooks/delete'
      path: '/api/public/webhooks/delete'
      fullPath: '/api/public/webhooks/delete'
      preLoaderRoute: typeof ApiPublicWebhooksDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/deliveries': {
      id: '/api/public/webhooks/deliveries'
      path: '/api/public/webhooks/deliveries'
      fullPath: '/api/public/webhooks/deliveries'
      preLoaderRoute: typeof ApiPublicWebhooksDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/list': {
      id: '/api/public/webhooks/list'
      path: '/api/public/webhooks/list'
      fullPath: '/api/public/webhooks/list'
      preLoaderRoute: typeof ApiPublicWebhooksListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/test': {
      id: '/api/public/webhooks/test'
      path: '/api/public/webhooks/test'
      fullPath: '/api/public/webhooks/test'
      preLoaderRoute: typeof ApiPublicWebhooksTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/toggle': {
      id: '/api/public/webhooks/toggle'
      path: '/api/public/webhooks/toggle'
      fullPath: '/api/public/webhooks/toggle'
      preLoaderRoute: typeof ApiPublicWebhooksToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedTrustRouteChildren {
  AuthenticatedTrustModerationRoute: typeof AuthenticatedTrustModerationRoute
}

const AuthenticatedTrustRouteChildren: AuthenticatedTrustRouteChildren = {
  AuthenticatedTrustModerationRoute: AuthenticatedTrustModerationRoute,
}

const AuthenticatedTrustRouteWithChildren =
  AuthenticatedTrustRoute._addFileChildren(AuthenticatedTrustRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedCapsuleRoute: typeof AuthenticatedCapsuleRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedCirclesRoute: typeof AuthenticatedCirclesRoute
  AuthenticatedCompanionRoute: typeof AuthenticatedCompanionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedReplayRoute: typeof AuthenticatedReplayRoute
  AuthenticatedSeasonsRoute: typeof AuthenticatedSeasonsRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRouteWithChildren
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedWrappedRoute: typeof AuthenticatedWrappedRoute
  AuthenticatedRoomCodeRoute: typeof AuthenticatedRoomCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedCapsuleRoute: AuthenticatedCapsuleRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedCirclesRoute: AuthenticatedCirclesRoute,
  AuthenticatedCompanionRoute: AuthenticatedCompanionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedReplayRoute: AuthenticatedReplayRoute,
  AuthenticatedSeasonsRoute: AuthenticatedSeasonsRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRouteWithChildren,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedWrappedRoute: AuthenticatedWrappedRoute,
  AuthenticatedRoomCodeRoute: AuthenticatedRoomCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicAuthGuardRouteChildren {
  ApiPublicAuthGuardSigninRoute: typeof ApiPublicAuthGuardSigninRoute
}

const ApiPublicAuthGuardRouteChildren: ApiPublicAuthGuardRouteChildren = {
  ApiPublicAuthGuardSigninRoute: ApiPublicAuthGuardSigninRoute,
}

const ApiPublicAuthGuardRouteWithChildren =
  ApiPublicAuthGuardRoute._addFileChildren(ApiPublicAuthGuardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  PhilosophyRoute: PhilosophyRoute,
  PrivacyRoute: PrivacyRoute,
  SdkRoute: SdkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAuthGuardRoute: ApiPublicAuthGuardRouteWithChildren,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicAiCompanionRoute: ApiPublicAiCompanionRoute,
  ApiPublicAiDashboardInsightsRoute: ApiPublicAiDashboardInsightsRoute,
  ApiPublicAiDiscoverPatternsRoute: ApiPublicAiDiscoverPatternsRoute,
  ApiPublicAiProactiveRoute: ApiPublicAiProactiveRoute,
  ApiPublicAiRecommendRoute: ApiPublicAiRecommendRoute,
  ApiPublicAiSessionRecapRoute: ApiPublicAiSessionRecapRoute,
  ApiPublicAiVaultSummarizeRoute: ApiPublicAiVaultSummarizeRoute,
  ApiPublicAiWeeklyStoryRoute: ApiPublicAiWeeklyStoryRoute,
  ApiPublicWebhooksCreateRoute: ApiPublicWebhooksCreateRoute,
  ApiPublicWebhooksDeleteRoute: ApiPublicWebhooksDeleteRoute,
  ApiPublicWebhooksDeliveriesRoute: ApiPublicWebhooksDeliveriesRoute,
  ApiPublicWebhooksListRoute: ApiPublicWebhooksListRoute,
  ApiPublicWebhooksTestRoute: ApiPublicWebhooksTestRoute,
  ApiPublicWebhooksToggleRoute: ApiPublicWebhooksToggleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
